//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-android v0.7
//
package com.beto4812.airqueue.aws;


import android.content.Context;
import android.util.Log;

import com.amazonaws.ClientConfiguration;
import com.amazonaws.regions.Region;
import com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient;

public class AWSClientManager {

    private static final String LOG_TAG = "AWSClientManager";

    private static AWSClientManager instance;

    private AmazonDynamoDBClient dynamoDBClient;
    private AWSIdentityManager identityManager;
    private AWSDynamoDbManager dynamoDbManager;
    private ClientConfiguration clientConfiguration;

    public AWSClientManager(Context context) {
        this.clientConfiguration = new ClientConfiguration();
        this.identityManager = new AWSIdentityManager(context, clientConfiguration);
        this.dynamoDBClient = new AmazonDynamoDBClient(identityManager.getCredentialsProvider(), clientConfiguration);
        dynamoDBClient.setRegion(Region.getRegion(AWSConstants.DYNAMO_REGION));
        this.dynamoDbManager = new AWSDynamoDbManager(dynamoDBClient);
        //initClients();
    }

    public AWSDynamoDbManager getDynamoDbManager() {
        return dynamoDbManager;
    }

    public AWSIdentityManager getIdentityManager(){
        return identityManager;
    }

    public static AWSClientManager defaultMobileClient() {
        return instance;
    }

    public static void setDefaultMobileClient(AWSClientManager client) {
        instance = client;
    }

    public static void initializeMobileClientIfNecessary(final Context context) {
        if (AWSClientManager.defaultMobileClient() == null) {
            Log.d(LOG_TAG, "Initializing AWS Mobile Client...");
            final ClientConfiguration clientConfiguration = new ClientConfiguration();
            //clientConfiguration.setUserAgent(AWSConfiguration.AWS_MOBILEHUB_USER_AGENT);
            final AWSIdentityManager identityManager = new AWSIdentityManager(context, clientConfiguration);
            final AWSClientManager awsClient =
                    new AWSClientManager(context);
            AWSClientManager.setDefaultMobileClient(awsClient);
        }
        Log.d(LOG_TAG, "AWS Mobile Client is OK");
    }

    private void initClients() {
        identityManager.getUserID(new AWSIdentityManager.IdentityHandler() {
            @Override
            public void handleIdentityID(String identityId) {
                Log.d(LOG_TAG, "handleIdentityID(): " + identityId);
            }
            @Override
            public void handleError(Exception exception) {
                Log.d(LOG_TAG, "initClients(): " + Log.getStackTraceString(exception));
            }
        });
    }
}